title: Dules
email: kelvin@dules.dev
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https:/dules.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kelvindules
github_username:  kelvindules

author: Kelvin Dules

# Build settings
markdown: GFM

remote_theme: "mmistakes/minimal-mistakes@4.22.0"
minimal_mistakes_skin: "dirt"
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      classes: wide
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

breadcrumbs: true

include: ["_pages"]

plugins:
  - jekyll-feed
  - jekyll-include-cache

repository: kelvindules/kelvindules.github.io